version: "3.7"
services:
  app:
    build:
      args:
        user: assessment
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: assessment
    container_name: assessment-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./assessment-app:/var/www
    networks:
      - assessment
  db:
    image : mysql
    container_name : mysql
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_assessment
      MYSQL_ROOT_PASSWORD: root
  #phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db
  # migration:
  #   image: app:latest
  #   command: ["./wait-for-it/wait-for-it.sh", "db:3306", "--", "npm", "run", "migrate"]
  #   links:
  #     - db
  #   depends_on:
  #     - db
  nginx:
    image: nginx:alpine
    container_name: nginx-assessment
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./assessment-app:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - assessment
networks:
  assessment:
    driver: bridge